<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ak_forum"
 *
 * Auto generated by Extension Builder 2019-12-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Just a forum',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Aristeidis Karavas',
    'author_email' => 'aristeidis.karavas@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '11.0.0-11.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
